name: Build Gtmate

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'true'



jobs:
  build:
    runs-on: ubuntu-latest

    services:
      squid-proxy:
        image: datadog/squid:latest
        ports:
          - 3128:3128
 
    steps:
    - name: Checkout
      uses: actions/checkout@v2

   
    - name: Setup Debug Session
      uses: csexton/debugger-action@master
